// Copyright 2021-2024 Takashi Takizawa. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
//
// Code generated by running go generate in github.com/ttkzw/go-color. DO NOT EDIT.

package color

// Foreground color name
const (
	// Default foreground color
	Default = Color(iota)

	/*
	 * system colors for foreground colors
	 */

	// Black for system foreground color
	SystemBlack

	// Red for system foreground color
	SystemRed

	// Green for system foreground color
	SystemGreen

	// Yellow for system foreground color
	SystemYellow

	// Blue for system foreground color
	SystemBlue

	// Magenta for system foreground color
	SystemMagenta

	// Cyan for system foreground color
	SystemCyan

	// White for system foreground color
	SystemWhite

	// BrightBlack for system foreground color
	SystemBrightBlack

	// BrightRed for system foreground color
	SystemBrightRed

	// BrightGreen for system foreground color
	SystemBrightGreen

	// BrightYellow for system foreground color
	SystemBrightYellow

	// BrightBlue for system foreground color
	SystemBrightBlue

	// BrightMagenta for system foreground color
	SystemBrightMagenta

	// BrightCyan for system foreground color
	SystemBrightCyan

	// BrightWhite for system foreground color
	SystemBrightWhite

	/*
	 * 8-bit colors for foreground colors
	 */

	// Red: HTML Hex Color Code #FF0000, Ansi 8-bit Color Index 196
	Red

	// Orange: HTML Hex Color Code #FF8700, Ansi 8-bit Color Index 208
	Orange

	// Yellow: HTML Hex Color Code #FFFF00, Ansi 8-bit Color Index 226
	Yellow

	// Chartreuse: HTML Hex Color Code #87FF00, Ansi 8-bit Color Index 118
	Chartreuse

	// Green: HTML Hex Color Code #00FF00, Ansi 8-bit Color Index 46
	Green

	// SpringGreen: HTML Hex Color Code #00FF87, Ansi 8-bit Color Index 48
	SpringGreen

	// Cyan: HTML Hex Color Code #00FFFF, Ansi 8-bit Color Index 51
	Cyan

	// Azure: HTML Hex Color Code #0087FF, Ansi 8-bit Color Index 33
	Azure

	// Blue: HTML Hex Color Code #0000FF, Ansi 8-bit Color Index 21
	Blue

	// Violet: HTML Hex Color Code #8700FF, Ansi 8-bit Color Index 93
	Violet

	// Magenta: HTML Hex Color Code #FF00FF, Ansi 8-bit Color Index 201
	Magenta

	// Rose: HTML Hex Color Code #FF0087, Ansi 8-bit Color Index 198
	Rose

	// White: HTML Hex Color Code #FFFFFF, Ansi 8-bit Color Index 231
	White

	// Silver: HTML Hex Color Code #BCBCBC, Ansi 8-bit Color Index 250
	Silver

	// Grey: HTML Hex Color Code #808080, Ansi 8-bit Color Index 244
	Grey

	// Black: HTML Hex Color Code #000000, Ansi 8-bit Color Index 16
	Black
)

var colorNames = []string{
	// Default foreground color
	"Default",

	/*
	 * system colors for foreground colors
	 */

	"SystemBlack",
	"SystemRed",
	"SystemGreen",
	"SystemYellow",
	"SystemBlue",
	"SystemMagenta",
	"SystemCyan",
	"SystemWhite",
	"SystemBrightBlack",
	"SystemBrightRed",
	"SystemBrightGreen",
	"SystemBrightYellow",
	"SystemBrightBlue",
	"SystemBrightMagenta",
	"SystemBrightCyan",
	"SystemBrightWhite",

	/*
	 * 8-bit colors for foreground colors
	 */

	"Red",
	"Orange",
	"Yellow",
	"Chartreuse",
	"Green",
	"SpringGreen",
	"Cyan",
	"Azure",
	"Blue",
	"Violet",
	"Magenta",
	"Rose",
	"White",
	"Silver",
	"Grey",
	"Black",
}

var colorParameters = [...]string{
	// Default foreground color
	Default: "39",

	/*
	 * system colors for foreground colors
	 */

	SystemBlack:         "30",
	SystemRed:           "31",
	SystemGreen:         "32",
	SystemYellow:        "33",
	SystemBlue:          "34",
	SystemMagenta:       "35",
	SystemCyan:          "36",
	SystemWhite:         "37",
	SystemBrightBlack:   "90",
	SystemBrightRed:     "91",
	SystemBrightGreen:   "92",
	SystemBrightYellow:  "93",
	SystemBrightBlue:    "94",
	SystemBrightMagenta: "95",
	SystemBrightCyan:    "96",
	SystemBrightWhite:   "97",

	/*
	 * 8-bit colors for foreground colors
	 */

	Red:         "38;5;196",
	Orange:      "38;5;208",
	Yellow:      "38;5;226",
	Chartreuse:  "38;5;118",
	Green:       "38;5;46",
	SpringGreen: "38;5;48",
	Cyan:        "38;5;51",
	Azure:       "38;5;33",
	Blue:        "38;5;21",
	Violet:      "38;5;93",
	Magenta:     "38;5;201",
	Rose:        "38;5;198",
	White:       "38;5;231",
	Silver:      "38;5;250",
	Grey:        "38;5;244",
	Black:       "38;5;16",
}

// Background color name
const (
	// Default background color
	DefaultBackground = BackgroundColor(iota)

	/*
	 * system colors for background colors
	 */

	// Black for system background color
	SystemBlackBackground

	// Red for system background color
	SystemRedBackground

	// Green for system background color
	SystemGreenBackground

	// Yellow for system background color
	SystemYellowBackground

	// Blue for system background color
	SystemBlueBackground

	// Magenta for system background color
	SystemMagentaBackground

	// Cyan for system background color
	SystemCyanBackground

	// White for system background color
	SystemWhiteBackground

	// BrightBlack for system background color
	SystemBrightBlackBackground

	// BrightRed for system background color
	SystemBrightRedBackground

	// BrightGreen for system background color
	SystemBrightGreenBackground

	// BrightYellow for system background color
	SystemBrightYellowBackground

	// BrightBlue for system background color
	SystemBrightBlueBackground

	// BrightMagenta for system background color
	SystemBrightMagentaBackground

	// BrightCyan for system background color
	SystemBrightCyanBackground

	// BrightWhite for system background color
	SystemBrightWhiteBackground

	/*
	 * 8-bit colors for background colors
	 */

	// Red for background color: HTML Hex Color Code #FF0000, Ansi 8-bit Color Index 196
	RedBackground

	// Orange for background color: HTML Hex Color Code #FF8700, Ansi 8-bit Color Index 208
	OrangeBackground

	// Yellow for background color: HTML Hex Color Code #FFFF00, Ansi 8-bit Color Index 226
	YellowBackground

	// Chartreuse for background color: HTML Hex Color Code #87FF00, Ansi 8-bit Color Index 118
	ChartreuseBackground

	// Green for background color: HTML Hex Color Code #00FF00, Ansi 8-bit Color Index 46
	GreenBackground

	// SpringGreen for background color: HTML Hex Color Code #00FF87, Ansi 8-bit Color Index 48
	SpringGreenBackground

	// Cyan for background color: HTML Hex Color Code #00FFFF, Ansi 8-bit Color Index 51
	CyanBackground

	// Azure for background color: HTML Hex Color Code #0087FF, Ansi 8-bit Color Index 33
	AzureBackground

	// Blue for background color: HTML Hex Color Code #0000FF, Ansi 8-bit Color Index 21
	BlueBackground

	// Violet for background color: HTML Hex Color Code #8700FF, Ansi 8-bit Color Index 93
	VioletBackground

	// Magenta for background color: HTML Hex Color Code #FF00FF, Ansi 8-bit Color Index 201
	MagentaBackground

	// Rose for background color: HTML Hex Color Code #FF0087, Ansi 8-bit Color Index 198
	RoseBackground

	// White for background color: HTML Hex Color Code #FFFFFF, Ansi 8-bit Color Index 231
	WhiteBackground

	// Silver for background color: HTML Hex Color Code #BCBCBC, Ansi 8-bit Color Index 250
	SilverBackground

	// Grey for background color: HTML Hex Color Code #808080, Ansi 8-bit Color Index 244
	GreyBackground

	// Black for background color: HTML Hex Color Code #000000, Ansi 8-bit Color Index 16
	BlackBackground
)

var backgroundColorNames = []string{
	// Default background color
	"Default",

	/*
	 * system colors for background colors
	 */

	"SystemBlack",
	"SystemRed",
	"SystemGreen",
	"SystemYellow",
	"SystemBlue",
	"SystemMagenta",
	"SystemCyan",
	"SystemWhite",
	"SystemBrightBlack",
	"SystemBrightRed",
	"SystemBrightGreen",
	"SystemBrightYellow",
	"SystemBrightBlue",
	"SystemBrightMagenta",
	"SystemBrightCyan",
	"SystemBrightWhite",

	/*
	 * 8-bit colors for background colors
	 */

	"Red",
	"Orange",
	"Yellow",
	"Chartreuse",
	"Green",
	"SpringGreen",
	"Cyan",
	"Azure",
	"Blue",
	"Violet",
	"Magenta",
	"Rose",
	"White",
	"Silver",
	"Grey",
	"Black",
}

var backgroundColorParameters = [...]string{
	// Default background color
	DefaultBackground: "49",

	/*
	 * system colors for background colors
	 */

	SystemBlackBackground:         "40",
	SystemRedBackground:           "41",
	SystemGreenBackground:         "42",
	SystemYellowBackground:        "43",
	SystemBlueBackground:          "44",
	SystemMagentaBackground:       "45",
	SystemCyanBackground:          "46",
	SystemWhiteBackground:         "47",
	SystemBrightBlackBackground:   "100",
	SystemBrightRedBackground:     "101",
	SystemBrightGreenBackground:   "102",
	SystemBrightYellowBackground:  "103",
	SystemBrightBlueBackground:    "104",
	SystemBrightMagentaBackground: "105",
	SystemBrightCyanBackground:    "106",
	SystemBrightWhiteBackground:   "107",

	/*
	 * 8-bit colors for background colors
	 */

	RedBackground:         "48;5;196",
	OrangeBackground:      "48;5;208",
	YellowBackground:      "48;5;226",
	ChartreuseBackground:  "48;5;118",
	GreenBackground:       "48;5;46",
	SpringGreenBackground: "48;5;48",
	CyanBackground:        "48;5;51",
	AzureBackground:       "48;5;33",
	BlueBackground:        "48;5;21",
	VioletBackground:      "48;5;93",
	MagentaBackground:     "48;5;201",
	RoseBackground:        "48;5;198",
	WhiteBackground:       "48;5;231",
	SilverBackground:      "48;5;250",
	GreyBackground:        "48;5;244",
	BlackBackground:       "48;5;16",
}
