name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Get
        run: go get .

      - name: Generate
        run: go generate .

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -o color cmd/color/main.go

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
            files: |
                color
