name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          [darwin_amd64, darwin_arm64, linux_amd64, linux_arm64, windows_amd64]
        include:
          - os: darwin_amd64
            goos: darwin
            arch: amd64
          - os: darwin_arm64
            goos: darwin
            arch: arm64
          - os: linux_amd64
            goos: linux
            arch: amd64
          - os: linux_arm64
            goos: linux
            arch: arm64
          - os: windows_amd64
            goos: windows
            arch: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Get
        run: go get .

      - name: Generate
        run: go generate .

      - name: Test
        run: go test -v ./...

      - name: Build
        run: |
          if [[ ${{ matrix.goos }} != "windows" ]]; then GOOS=${{ matrix.goos }} GOARCH=${{ matrix.arch }} go build -o color cmd/color/main.go; fi
          if [[ ${{ matrix.goos }} == "windows" ]]; then GOOS=${{ matrix.goos }} GOARCH=${{ matrix.arch }} go build -o color.exe cmd/color/main.go; fi

      - name: Archive
        run: |
          if [[ ${{ matrix.goos }} != "windows" ]]; then zip color-${{ matrix.goos }}-${{ matrix.arch }}.zip color; fi
          if [[ ${{ matrix.goos }} == "windows" ]]; then zip color-${{ matrix.goos }}-${{ matrix.arch }}.zip color.exe; fi

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
            files: |
                color-${{ matrix.goos }}-${{ matrix.arch }}.zip
